// THIS FILE IS GENERATED - DO NOT MODIFY
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
export const PROJECT_NPM_NAME = 'tnp-core';
export const CURRENT_PACKAGE_VERSION = '19.0.34';
// THIS FILE IS GENERATED - DO NOT MODIFY
      